<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)'=='RELEASE'">
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(BuildAsConsoleApplication)'=='true'">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GammaRay.Client.GUI\GammaRay.Client.GUI.csproj" />
  </ItemGroup>
</Project>
