api:
  endPoints:
    - bindAddress: 127.0.0.3
      port: 5000

inbounds:
  hostHttpIn: http://127.0.0.3:2000
  hostSocksIn:
    protocol: socks
    endPoint: 127.0.0.3:2001

internetAccessPoints:
  finlandProxy:
    channels:
      vless-reality-xhttp:
        protocol: socks
        endPoint: 127.0.0.1:20000
        tags: []
        availableInNetwork: [ default ]

capabilityClasses:
  HTTPS:
    detectionRules:
      - transport: StreamBased
        port: 443
    probingMethod:
      driver: HTTP
      parameters:
        useTLS: true
        path: ""
        method: GET
  HTTP:
    detectionRules:
      - transport: StreamBased
        port: 80
    probingMethod:
      driver: HTTP
      parameters:
        useTLS: false
        path: ""
        method: GET

endpointRoutingConfigurations:
  default:
    IAPChain: [ [local:*, finlandProxy] ]
    defaultIAPChain: [ finlandProxy, local:* ]

  ruDomains:
    IAPChain: [ [local:*], [finlandProxy] ]
    defaultIAPChain: [ local:* ]

  viaProxy:
    IAPChain: [ [finlandProxy] ]
    queueMode: restricted

  viaLocal:
    IAPChain: [ [local:*] ]
    queueMode: restricted

networkProfiles: {}

endPointCategories:
  ruDomains: { patterns: [ ru ] }
  blockedInRussia: { patternsListFile: blocked.txt }
  blockedInNonRussia: { patternsListFile: local.txt }

routingRules:
  - endPointCategory: blockedInRussia
    networkProfile: default  
    to: viaProxy

  - endPointCategory: blockedInNonRussia
    to: viaLocal

  - endPointCategory: ruDomains
    to: ruDomains

  - to: default
