<Project>
  <ItemGroup>
    <!-- Basic MS packages -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <!-- Database packages -->
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <!-- gRPC packages -->
    <PackageVersion Include="Grpc.Core" Version="2.46.6" />
    <PackageVersion Include="Grpc.Tools" Version="2.81.1" />
    <PackageVersion Include="Google.Protobuf" Version="3.35.1" />
    <!-- Other packages -->
    <PackageVersion Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageVersion Include="YamlDotNet" Version="18.0.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.11" />
    <!-- Avalonia packages -->
    <PackageVersion Include="Avalonia" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="12.0.1" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="12.0.3" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.5" />
  </ItemGroup>
</Project>
