<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildAsExecutable)' == 'true'">
    <OutputType>exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishAot>true</PublishAot>
    <DefineConstants>$(DefineConstants);BuildAsExecutable</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\GammaRay.Core\GammaRay.Core.csproj" />
  </ItemGroup>

</Project>
