syntax = "proto3";

package GammaRay.Core.API;

import "google/protobuf/timestamp.proto";
import "API/Services/common.proto";

option csharp_namespace = "GammaRay.Core.API.Services.Proto";

service MonitoringService {
	rpc SubscribeEvents(Empty) returns (stream MonitoringEvent);
}

message MonitoringEvent {
	oneof event {
		NewProcedureEvent newProcedure = 1;
		CommitReportEvent commitReport = 2;
		FinishProcedureEvent finishProcedure = 3;
	}

	enum SyncronizationType {
		NonBuffered = 0;
		Buffered = 1;
		LastBuffered = 2;
	}
	SyncronizationType type = 5;
}

message NewProcedureEvent {
	Guid procedureId = 1;
	string type = 2;
	google.protobuf.Timestamp creationTime = 3;
}

message CommitReportEvent {
	Guid procedureId = 1;
	string classIdentification = 2;
	map<string, string> jsonReport = 3;
}

message FinishProcedureEvent {
	Guid procedureId = 1;
	bool isSuccessful = 2;
	string exceptionMessage = 3;
}
