syntax = "proto3";

package GammaRay.Core.API;

import "google/protobuf/timestamp.proto";

option csharp_namespace = "GammaRay.Core.API.Proto";

service GammaRayService {
	rpc GetAPIVersion(Empty) returns (VersionResponse);
	rpc GetCurrentSettingsFile(Empty) returns (SettingsFileResponse);
	rpc UploadNewSettingsFile(SettingsFileRequest) returns (Empty);
	rpc ReloadApplication(Empty) returns (Empty);
	rpc SubscribeEvents(Empty) returns (stream MonitoringEvent);
}

message Empty { }

message VersionResponse {
	int32 version = 1;
}

message SettingsFileResponse {
	string content = 1;
}

message SettingsFileRequest {
	string content = 1;
}

message MonitoringEvent {
	oneof event {
		NewProcedureEvent newProcedure = 1;
		CommitReportEvent commitReport = 2;
		FinishProcedureEvent finishProcedure = 3;
	}

	enum SyncronizationType {
		NonBuffered = 0;
		Buffered = 1;
		LastBuffered = 2;
	}
	SyncronizationType type = 5;
}

message NewProcedureEvent {
	bytes procedureId = 1;
	string type = 2;
	google.protobuf.Timestamp creationTime = 3;
}

message CommitReportEvent {
	bytes procedureId = 1;
	string classIdentification = 2;
	map<string, string> jsonReport = 3;
}

message FinishProcedureEvent {
	bytes procedureId = 1;
	bool isSuccessful = 2;
	string exceptionMessage = 3;
}
