<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefineConstants Condition="'$(Configuration)'=='DEBUG'">$(DefineConstants);EnablePIDGather</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Nito.AsyncEx.Context" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
   
  <ItemGroup>
    <Protobuf Include="API\Services\common.proto" />
    <Protobuf Include="API\Services\ChannelsService.proto" />
    <Protobuf Include="API\Services\ServicesService.proto" />
    <Protobuf Include="API\Services\MonitoringService.proto" />
    <Protobuf Include="API\Services\ControlService.proto" />
    <Protobuf Include="API\Services\NetworkService.proto" />
    <Protobuf Include="API\Services\BasicService.proto" />
    <Protobuf Include="API\Services\FileSystemService.proto" />
  </ItemGroup>

</Project>
