<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Tools" Version="2.81.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="YamlDotNet" Version="18.0.0" />
  </ItemGroup>
   
  <ItemGroup>
    <Protobuf Include="API\Services\common.proto" />
    <Protobuf Include="API\Services\ChannelsService.proto" />
    <Protobuf Include="API\Services\ServicesService.proto" />
    <Protobuf Include="API\Services\MonitoringService.proto" />
    <Protobuf Include="API\Services\ControlService.proto" />
    <Protobuf Include="API\Services\NetworkService.proto" />
    <Protobuf Include="API\Services\SettingsService.proto" />
    <Protobuf Include="API\Services\BasicService.proto" />
  </ItemGroup>

</Project>
