<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup>
    <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.AOT" Version="1.0.48" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
    <PackageReference Include="Nito.AsyncEx.Context" Version="5.1.2" />
    <PackageReference Include="Serilog" Version="4.3.0" />
  </ItemGroup>

</Project>
